### ISSUE TITLE
renderer:didAddNode:forAnchor: not called

### ISSUE THREAD

**Issue by PascoCoder** [markdaws/arkit-by-example#5]
I run the part 2 of your arkit examples，but there was no grid. I set breakpoint in `renderer:didAddNode:forAnchor:`,just found it was not called.
![image](https://user-images.githubusercontent.com/14069728/28448012-4cae73a6-6e07-11e7-910d-8ae21a63ab1f.png)
now i dont know where goes wrong.

**Comment by venky05** [comment]
delegate methods are not trigging that's the reason it is not coming to break point

**Comment by rom4in** [comment]
you need to 'scan' the real world more until it ark detects planes. Make sure you have plane detection set to .horizontal

**Comment by markdaws** [comment]
@PascoCoder - did you get this to work?  As rom4in mentioned ARKit might not be detecting planes. It can only detect horizontal planes like floors of table top surfaces, not vertical planes like walls of angled planes etc. Also in order to detect planes it needs to have plenty of feature points in the video stream to track such as varied textures, if you are pointing at a solid color surface e.g. a white table top or something shiny (a glass table top) ARKit won't be able to detect that plane.

**Comment by PascoCoder** [comment]
thx...There were not enough feature points, so no planes were detected
